### ISSUE TITLE
Bug: We set allowed_clients but that isn't something that is about origins/URLs

### ISSUE THREAD

**Issue by alexrussell** [romainbessugesmeusy/netlify-plugin-auth0-patch-urls#11]
The plugin [sets `allowed_clients`](https://github.com/romainbessugesmeusy/netlify-plugin-auth0-patch-urls/blob/master/index.js#L66-L68) on the Auth0 client, but while I don't know what it refers to in the Auth0 client (application) UI, the API docs suggests it's not related to origins/URLs:

> List of allow clients and API ids that are allowed to make delegation requests. Empty means all all your clients are allowed.

Is it a bug that the plugin sets this to be the preview URLs?

**Comment by romainbessugesmeusy** [comment]
I'd say it's something that I tried at first and stayed without being questioned. For reference, here they are in the UI. Will be deleted in 1.2.0
![Capture d’écran 2020-06-03 à 10 50 11](https://user-images.githubusercontent.com/3127404/83616357-079bae80-a588-11ea-8ac4-e406f7b2b68a.png)
