### ISSUE TITLE
Bug: `allowed_logout_urls` copies data from `callbacks`, is this right?

### ISSUE THREAD

**Issue by alexrussell** [romainbessugesmeusy/netlify-plugin-auth0-patch-urls#4]
Much like the work done in #2 to fix a couple of typos, is there another typo of `callbacks` instead of `allowed_logout_urls` in [`index.js:82`](https://github.com/romainbessugesmeusy/netlify-plugin-auth0-patch-urls/blob/master/index.js#L82) that also needs to be renamed, or is this on purpose?

Happy to PR it, just asking before I do (though I imagine it'd be quicker for you to do the fix without the PR as you need to manually bump and release anyway).

**Comment by tnovau** [comment]
@romainbessugesmeusy addressing this in #12
