### ISSUE TITLE
Docs: Document forms of the pathnames env vars

### ISSUE THREAD

**Issue by alexrussell** [romainbessugesmeusy/netlify-plugin-auth0-patch-urls#5]
It'd be great to document how to write the two pathnames env vars (`AUTH0_CALLBACK_PATHNAMES` and `AUTH0_LOGOUT_PATHNAMES`). I had to look at the source to see it was the pathname without origin (obvious) or initial slash (not so obvious) and separated by commas (common sense, but not obvious).

Maybe examples will do the job.

**Comment by romainbessugesmeusy** [comment]
Will remove CALLBACK_PATHNAMES and AUTH0_LOGOUT_PATHNAMES in favor of wildcard subdomains.
